name: Report a Bug
description: Report an InceptusNMS Bug.
labels: ['unconfirmed bug']
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a n InceptusNMS bug. Please take time to fill out the information below.
- type: dropdown
  attributes:
    label: Bug Type
    description: What type of bug are you trying to report?
    multiple: true
    options:
      - Documentation Errors
      - Typos
      - JavaDoc Errors
      - Other Unexpected Behavior
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    placeholder: |
      Ex: "Links not being shown"
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      In the box below, you can attach any relevant info or files that may help us solve the bug.
      If you think this issue is relevant to any other issues, please mention it here.
- type: textarea
  attributes:
    label: Additional Info
    description: Any additional info that may help us solve the bug.
    placeholder: |
      Ex: "Located on page Component"
  validations:
      required: false