name: Build Project

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Projects
        run: ./gradlew project tasks dependencies

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    name: Generate JavaDocs
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Generate JavaDocs
        run: ./gradlew clean generate
      - name: Deploy JavaDocs
        run: bash javadoc.sh ${GITHUB_SHA::7}
