name: Validate PR

on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Projects
        run: ./gradlew project tasks dependencies
      - name: Validate Pull Request
        run: ./gradlew validate
    